### ISSUE TITLE
PROJECT_PHOTO не работает

### ISSUE THREAD

**Issue by jieggii** [AlexGyver/GyverCheat#1]
Спешу сообщить, что ты скорее всего забыл залить на гитхаб фото проекта (proj_img.png).

**Comment by aquaminer** [comment]
@jieggii и не только) страница проекта - 404, видео также нет. Проще говоря проект WIP

**Comment by aquaminer** [comment]
@AlexGyver спешу оповестить вас о доступной фиче "приватный репозиторий", она позволит вам скрыть репозиторий пока вы его "готовите". Удачи 😄

**Comment by AlexGyver** [comment]
> @AlexGyver спешу оповестить вас о доступной фиче "приватный репозиторий", она позволит вам скрыть репозиторий пока вы его "готовите". Удачи

Фича платная. Пока видео не вышло - репозиторий не завершён
